### ISSUE TITLE
Failed silent login, interactive login required

### ISSUE THREAD

**Issue by AnoXDD** [OneDrive/onedrive-sdk-android#119]
It sounds like an old issue and I was spending the last several days trying to fix it but no. 

# Error
The error was
```
03-10 23:07:42.636 8614-8759/com.microsoft.onedrive.onedriveapiexplorer E/MSAAuthenticator$5[onAuthComplete] - 314: Failed silent login, interactive login required
                                                                                                                    com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
                                                                                                                        at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
                                                                                                                        at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
                                                                                                                        at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
                                                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                                        at java.lang.Thread.run(Thread.java:818)
```

And other information will be posted as a follow up.

# Tested on
I used both my Nexus 4 (5.1.1, API 22) and Nexus 6 (API 23) to run the same code on [onedrive-explorer-android](https://github.com/OneDrive/onedrive-explorer-android) and it gave me the same error saying that silent login failed. 

The exact same code worked on both of them compiled last summer, and now I got this error. I'll be glad to provide any additional logcat if necessary.

**Comment by AnoXDD** [comment]
Logcat of the entire session

```
03-10 23:19:13.507 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/art: Late-enabling -Xcheck:jni
03-10 23:19:13.658 12883-12907/com.microsoft.onedrive.onedriveapiexplorer D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-10 23:19:13.664 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/Atlas: Validating map...
03-10 23:19:13.696 12883-12907/com.microsoft.onedrive.onedriveapiexplorer I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/15/15, ab0075f, Id3510ff6dc
03-10 23:19:13.697 12883-12907/com.microsoft.onedrive.onedriveapiexplorer I/OpenGLRenderer: Initialized EGL, version 1.4
03-10 23:19:13.719 12883-12907/com.microsoft.onedrive.onedriveapiexplorer D/OpenGLRenderer: Enabling debug mode 0
03-10 23:19:17.765 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/BaseApplication[createConfig] - 99: Setting logging level to Debug
03-10 23:19:17.766 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/DefaultClientConfig[getExecutors] - 148: Created DefaultExecutors
03-10 23:19:17.786 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/DefaultClientConfig[getSerializer] - 135: Created DefaultSerializer
03-10 23:19:17.787 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/DefaultClientConfig[getHttpProvider] - 122: Created DefaultHttpProvider
03-10 23:19:17.788 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/DefaultExecutors[performOnBackground] - 67: Starting background task, current active count: 0
03-10 23:19:17.796 12883-12993/com.microsoft.onedrive.onedriveapiexplorer D/MSAAuthenticator[loginSilent] - 294: Starting login silent
03-10 23:19:17.800 12883-12993/com.microsoft.onedrive.onedriveapiexplorer D/MSAAuthenticator[loginSilent] - 336: MSA silent auth fast-failed
03-10 23:19:17.800 12883-12993/com.microsoft.onedrive.onedriveapiexplorer D/MSAAuthenticator[login] - 190: Starting login
03-10 23:19:17.801 12883-12993/com.microsoft.onedrive.onedriveapiexplorer D/MSAAuthenticator[login] - 229: Waiting for MSA callback
03-10 23:19:17.806 12883-12996/com.microsoft.onedrive.onedriveapiexplorer I/LiveAuthClient: No refresh token available, sorry!
03-10 23:19:17.806 12883-12996/com.microsoft.onedrive.onedriveapiexplorer I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
03-10 23:19:17.841 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/WebViewFactory: Loading com.google.android.webview version 51.0.2704.81 (code 270408100)
03-10 23:19:17.841 12883-12996/com.microsoft.onedrive.onedriveapiexplorer E/MSAAuthenticator$5[onAuthComplete] - 314: Failed silent login, interactive login required
                                                                                                                      com.onedrive.sdk.authentication.ClientAuthenticatorException: Failed silent login, interactive login required
                                                                                                                          at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:312)
                                                                                                                          at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
                                                                                                                          at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
                                                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                                          at java.lang.Thread.run(Thread.java:818)
03-10 23:19:17.855 12883-12998/com.microsoft.onedrive.onedriveapiexplorer I/LiveAuthClient: No refresh token available, sorry!
03-10 23:19:17.855 12883-12998/com.microsoft.onedrive.onedriveapiexplorer I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
03-10 23:19:17.855 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/cr_LibraryLoader: Time to load native libraries: 4 ms (timestamps 7837-7841)
03-10 23:19:17.856 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/cr_LibraryLoader: Expected native library version number "51.0.2704.81", actual native library version number "51.0.2704.81"
03-10 23:19:17.856 12883-12998/com.microsoft.onedrive.onedriveapiexplorer D/MSAAuthenticator$2[onAuthComplete] - 201: Received invalid login failure from silent authentication with MSA, ignoring.
03-10 23:19:17.872 12883-12883/com.microsoft.onedrive.onedriveapiexplorer V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {1888a932}
03-10 23:19:17.872 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/cr_LibraryLoader: Expected native library version number "51.0.2704.81", actual native library version number "51.0.2704.81"
03-10 23:19:17.872 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
03-10 23:19:17.911 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
03-10 23:19:17.932 12883-12883/com.microsoft.onedrive.onedriveapiexplorer E/ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
03-10 23:19:17.933 12883-12883/com.microsoft.onedrive.onedriveapiexplorer E/ApkAssets: Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
03-10 23:19:18.016 12883-13021/com.microsoft.onedrive.onedriveapiexplorer W/cr_media: Requires BLUETOOTH permission
03-10 23:19:18.055 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
03-10 23:19:18.056 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
03-10 23:19:18.099 12883-13025/com.microsoft.onedrive.onedriveapiexplorer D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
03-10 23:19:18.127 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
03-10 23:19:18.127 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
03-10 23:19:18.152 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:30] Constructor
03-10 23:19:18.162 12883-12883/com.microsoft.onedrive.onedriveapiexplorer W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
03-10 23:19:18.163 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
03-10 23:19:18.175 12883-12883/com.microsoft.onedrive.onedriveapiexplorer I/cr_Ime: ImeThread is not enabled.
03-10 23:19:18.215 12883-13025/com.microsoft.onedrive.onedriveapiexplorer D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
03-10 23:19:18.246 12883-13034/com.microsoft.onedrive.onedriveapiexplorer E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
03-10 23:19:18.360 12883-13034/com.microsoft.onedrive.onedriveapiexplorer I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
03-10 23:19:19.141 12883-12883/com.microsoft.onedrive.onedriveapiexplorer W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12883
03-10 23:19:19.142 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: true
03-10 23:19:19.142 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:68] hideSoftInputFromWindow
03-10 23:19:20.166 12883-12883/com.microsoft.onedrive.onedriveapiexplorer W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12883
03-10 23:19:20.583 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
03-10 23:19:20.587 12883-12883/com.microsoft.onedrive.onedriveapiexplorer D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [0, 0], COM [-1, -1]
```

**Comment by AnoXDD** [comment]
Run clean and rebuild the project somehow fixed the issue.
