### ISSUE TITLE
java.util.NoSuchElementException at java.util.Scanner.next(Scanner.java:968)

### ISSUE THREAD

**Issue by mvysny** [OneDrive/onedrive-sdk-android#123]
Good day, I'm using `onedrive-sdk-android-1.2.2` and my app's Crashlytics is reporting the following stacktrace:
```
Non-fatal Exception: com.onedrive.sdk.core.ClientException: Error during http request
       at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:309)
       at com.onedrive.sdk.http.DefaultHttpProvider.send(DefaultHttpProvider.java:165)
       at com.onedrive.sdk.http.BaseCollectionRequest.send(BaseCollectionRequest.java:82)
       at com.onedrive.sdk.generated.BaseItemCollectionRequest.get(BaseItemCollectionRequest.java:69)
       at sk.baka.photoframe.fsimpl.onedrive.OneDriveFileSystem2.list(OneDriveFileSystem2.kt:18)
       at sk.baka.photoframe.fs.CacheFileSystem.list(CacheFileSystem.java:104)
       at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
       at sk.baka.photoframe.browser.DirContentsLoader.loadItemsInBackground(FSBrowserView.kt:341)
       at sk.baka.aedict.util.LoaderEx$Loader.run(LoaderEx.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.util.NoSuchElementException
       at java.util.Scanner.next(Scanner.java:968)
       at java.util.Scanner.next(Scanner.java:941)
       at com.onedrive.sdk.http.DefaultHttpProvider.streamToString(DefaultHttpProvider.java:388)
       at com.onedrive.sdk.http.OneDriveServiceException.createFromConnection(OneDriveServiceException.java:299)
       at com.onedrive.sdk.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:339)
       at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:252)
       at com.onedrive.sdk.http.DefaultHttpProvider.send(DefaultHttpProvider.java:165)
       at com.onedrive.sdk.http.BaseCollectionRequest.send(BaseCollectionRequest.java:82)
       at com.onedrive.sdk.generated.BaseItemCollectionRequest.get(BaseItemCollectionRequest.java:69)
       at sk.baka.photoframe.fsimpl.onedrive.OneDriveFileSystem2.list(OneDriveFileSystem2.kt:18)
       at sk.baka.photoframe.fs.CacheFileSystem.list(CacheFileSystem.java:104)
       at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
       at sk.baka.photoframe.browser.DirContentsLoader.loadItemsInBackground(FSBrowserView.kt:341)
       at sk.baka.aedict.util.LoaderEx$Loader.run(LoaderEx.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```
This looks very similar to #81 yet I can't say whether it's the same issue or not. I also do not have any information from the user regarding of whether there are any special characters in the file name or not. Thanks! :)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
