### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by mvysny** [OneDrive/onedrive-sdk-android#125]
In the SDK v 1.2.2, I have one report of the following bug which I fail to reproduce:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
       at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:286)
       at com.onedrive.sdk.http.DefaultHttpProvider.send(DefaultHttpProvider.java:165)
       at com.onedrive.sdk.http.BaseStreamRequest.send(BaseStreamRequest.java:76)
       at com.onedrive.sdk.generated.BaseItemStreamRequest.get(BaseItemStreamRequest.java:60)
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
