### ISSUE TITLE
App crashes when we select OneDrive Business after username

### ISSUE THREAD

**Issue by sam-devstudio** [OneDrive/onedrive-sdk-android#149]
When we try to select one Drive Business on an simple account we get a crash with following exception
E/DisambiguationAuthenticator$2[failure] - 190: Unable to disambiguate account type
com.onedrive.sdk.authentication.ClientAuthenticatorException: Unable to disambiguate account type
at com.onedrive.sdk.authentication.DisambiguationAuthenticator$2.failure(DisambiguationAuthenticator.java:187)
at com.onedrive.sdk.authentication.DisambiguationWebView.onReceivedError(DisambiguationWebView.java:89)
at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:267)
at uv.a(SourceFile:1)
at xH.a(SourceFile:255)
at ayK.handleMessage(SourceFile:38)

I have tried to add try catch but no success.

**Comment by saqibmirza2007** [comment]
When we try to select one Drive Business on an simple account we get a crash with following exception 
E/DisambiguationAuthenticator$2[failure] - 190: Unable to disambiguate account type
    com.onedrive.sdk.authentication.ClientAuthenticatorException: Unable to disambiguate account type
        at com.onedrive.sdk.authentication.DisambiguationAuthenticator$2.failure(DisambiguationAuthenticator.java:187)
        at com.onedrive.sdk.authentication.DisambiguationWebView.onReceivedError(DisambiguationWebView.java:89)
        at android.webkit.WebViewClient.onReceivedError(WebViewClient.java:267)
        at uv.a(SourceFile:1)
        at xH.a(SourceFile:255)
        at ayK.handleMessage(SourceFile:38)

I have tried to add try catch but no success.

**Comment by sam-devstudio** [comment]
Anyone from Microsoft or someone else can look into this and help ?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
