### ISSUE TITLE
OneCloud fails on Android 9 with NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient

### ISSUE THREAD

**Issue by mvysny** [OneDrive/onedrive-sdk-android#150]
com.onedrive.sdk:onedrive-sdk-android:1.2.2

```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
       at com.microsoft.services.msa.LiveAuthClient.<init>(LiveAuthClient.java:253)
       at com.microsoft.services.msa.LiveAuthClient.<init>(LiveAuthClient.java:318)
       at com.onedrive.sdk.authentication.MSAAuthenticator.init(MSAAuthenticator.java:143)
       at com.onedrive.sdk.authentication.DisambiguationAuthenticator.init(DisambiguationAuthenticator.java:129)
       at com.onedrive.sdk.extensions.OneDriveClient$Builder.loginAndBuildClient(OneDriveClient.java:163)
       at com.onedrive.sdk.extensions.OneDriveClient$Builder$1.run(OneDriveClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by KrawczykPawel** [comment]
I have the same issue, please try to use this:

To continue using the Apache HTTP client, apps that target Android 9 and above can add the following to their AndroidManifest.xml:
<uses-library android:name="org.apache.http.legacy" android:required="false"/>

More details
https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p

**Comment by mvysny** [comment]
Thank you, that's exactly what I added to the manifest XML in the newest photocloud version (already present in Google play), so hopefully this bug should be fixed now.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
