### ISSUE TITLE
OneDrive Business access.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#20]
Does it possible to view files on OneDrive Business cloud with your [onedrive-explorer-android](https://github.com/OneDrive/onedrive-explorer-android/tree/master/app/src/main/java/com/microsoft/onedrive/apiexplorer)? I have changed

```
private IClientConfig createConfig() {
    final MSAAuthenticator msaAuthenticator = new MSAAuthenticator() {
        @Override
        public String getClientId() {
            return "000000004C146A60";
        }

        @Override
        public String[] getScopes() {
            return new String[] {"onedrive.readwrite", "onedrive.appfolder", "wl.offline_access"};
        }
    };

    final IClientConfig config = DefaultClientConfig.createWithAuthenticator(msaAuthenticator);
    config.getLogger().setLoggingLevel(LoggerLevel.Debug);
    return config;
}
```

to

```
private IClientConfig createConfig() {
    final ADALAuthenticator adalAuthenticator = new ADALAuthenticator() {
        @Override
        public String getClientId() {
            return "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"; //Clien ID from Azure AD account
        }

        @Override
        protected String getRedirectUrl() {
            return "http://BestCrypt"; //Redirect URL from Azure AD account
        }
    };

    final IClientConfig config = DefaultClientConfig.createWithAuthenticator(adalAuthenticator);
    config.getLogger().setLoggingLevel(LoggerLevel.Debug);
    return config;
}
```

in BaseApplication class and have got this exception when trying to view root of the cloud:

```
12-04 20:59:06.752    7129-7545/com.microsoft.onedrive.onedriveapiexplorer E/DefaultHttpProvider[sendRequestInternal] - 297﹕ OneDrive Service exception GET https://jetico-my.sharepoint.com/_api/v2.0/me/drive/items/root?expand=children%2Cthumbnails
X-RequestStats : SDK-Version=Android-v1.0
Authorization : bearer null
401 : Unauthorized
X-MS-InvokeApp : 1; RequireReadOnly
SPRequestDuration : 8
SPRequestGuid : ddfa479d-2028-2000-4650-5aa8336a17a1
x-ms-diagnostics : 3000006;reason="Token contains invalid signature.";category="invalid_client"
request-id : ddfa479d-2028-2000-4650-5aa8336a17a1
X-Powered-By : ASP.NET
WWW-Authenticate : Bearer realm="2285ee43-8a18-451a-9003-d2b9149ff447",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"
X-Android-Response-Source : NETWORK 401
MicrosoftSharePointTeamServices : 16.0.0.4705
X-Android-Sent-Millis : 1449241146594
P3P : CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
Date : Fri, 04 Dec 2015 14:59:08 GMT
X-Content-Type-Options : nosniff
X-FRAME-OPTIONS : SAMEORIGIN
Content-Length : 51
Server : Microsoft-IIS/8.5
SPIisLatency : 2
Strict-Transport-Security : max-age=31536000
X-Android-Received-Millis : 1449241146721
{
"error_description": "Unsupported security token."
}
com.onedrive.sdk.http.OneDriveServiceException: GET https://jetico-my.sharepoint.com/_api/v2.0/me/drive/items/root?expand=children%2Cthumbnails
X-RequestStats : SDK-Version=Android-v1.0
Authorization : bearer null
401 : Unauthorized
[...]
[Some information was truncated for brevity, enable debug logging for more details]
        at com.onedrive.sdk.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:329)
        at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:243)
        at com.onedrive.sdk.http.DefaultHttpProvider.access$000(DefaultHttpProvider.java:48)
        at com.onedrive.sdk.http.DefaultHttpProvider$1.run(DefaultHttpProvider.java:127)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

I have [Azure Active Directory Premium free for one month](https://azure.microsoft.com/en-gb/trial/get-started-active-directory/) tuned according to the manual [Integrating Azure AD into a Java](https://azure.microsoft.com/ru-ru/documentation/samples/active-directory-java-native-headless/)

Should I take some additional steps in order to do not get

```
Authorization : bearer null
```

in the log?

**Comment by peternied** [comment]
RE: The bearer token, this is by design because I don't want developers to accidentally expose a valid bearer token when posting service errors.  You can uncomment it for development purposes; I typically stick a break point on `getAccessToken()`.

**Comment by peternied** [comment]
To your question, Yes it does support being switched to the an AdalAuthenticator or to use a MSA and ADAL authenticator together.  Based on the unauthorized error, it sounds like your application might not have the scopes granted for the `files` api, see this for details on configuring your application in azure https://dev.onedrive.com/app-registration.htm#register-your-app-for-onedrive-for-business

**Comment by isabsent** [comment]
Do you mean 

```
5. Specify the permission levels your app requires from the Office 365 API applications in Azure using scopes.
```

? 
I have thought it is configured in mobile app code (as it is for simple OneDrive). Should I go to Azure AD and grant this scope from there?

**Comment by peternied** [comment]
Yup

**Comment by isabsent** [comment]
Did you mean this settings:

```
Read and write all groups
Read all groups
Read and write directory data
Access the directory as the signed-in user
Read directory data
Read all users' full profiles
Read all users' basic profiles
Sign in and read user profile
```

?
I have set 8 checkboxes without any result.

**Comment by peternied** [comment]
You'll need to configure specifically Office 365 SharePoint Online to have read/write permissions to files
![image](https://cloud.githubusercontent.com/assets/2754967/11599732/522b1bae-9a7d-11e5-93b6-faf3f3ee6ae2.png)

**Comment by isabsent** [comment]
It works! Thanks a lot. It was very tricky...
