### ISSUE TITLE
Update method problem for OneDrive Business.

### ISSUE THREAD

**Issue by isabsent** [OneDrive/onedrive-sdk-android#23]
I am using this code

```
Item updatedItem = new Item();
updatedItem.name = name;
updatedItem.parentReference = new ItemReference();
updatedItem.parentReference.id = parentId;
itemRenamed[0] = service
    .getDrive()
    .getItems(item.id)
    .buildRequest()
    .update(updatedItem);
```

for **renaming** a file in the same folder (name is changed, parentId isn't changed) or for **moving** it from one cloud folder to another cloud folder (name isn't changed, parentId is changed). I have implemented this [X-HTTP-Method-Override workaround](https://github.com/OneDrive/onedrive-sdk-android/issues/16) to get it working on a device with API level 16. It works fine inside of OneDrive, but gives an exception on a device with API level 16 inside of OneDrive Business:

```
12-05 21:28:03.751  21212-22076/com.jetico.bestcrypt E/DefaultHttpProvider[sendRequestInternal] - 297﹕ OneDrive Service exception Error code: -1, Microsoft.SharePoint.Client.InvalidClientQueryException
Error message: Параметр name не существует в методе GetById. //Parameter name doesn't exist in method GetById (Translation from my native language).
POST https://jetico-my.sharepoint.com/_api/v2.0/me/drive/items/01TA3NVNQMHU54P3GEYJGZNLJNSVESVDXW
X-RequestStats : SDK-Version=Android-v1.0.1
Authorization : bearer XXXXXXXXXXXXXXXXXXXXXXXXXXX[...]
{"name":"asg.txt","parentReference":{"id":"root"}}[...]
400 : Bad Request
[...]
[Some information was truncated for brevity, enable debug logging for more details]
com.onedrive.sdk.http.OneDriveServiceException: Error code: -1, Microsoft.SharePoint.Client.InvalidClientQueryException
Error message: Параметр name не существует в методе GetById. //Parameter name doesn't exist in method GetById (Translation from my native language).
POST https://jetico-my.sharepoint.com/_api/v2.0/me/drive/items/01TA3NVNQMHU54P3GEYJGZNLJNSVESVDXW
X-RequestStats : SDK-Version=Android-v1.0.1
Authorization : bearer XXXXXXXXXXXXXXXXXXXXXXXXXXX[...]
{"name":"asg.txt","parentReference":{"id":"root"}}[...]
400 : Bad Request
[...]
[Some information was truncated for brevity, enable debug logging for more details]
        at com.onedrive.sdk.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:329)
        at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:243)
        at com.onedrive.sdk.http.DefaultHttpProvider.send(DefaultHttpProvider.java:154)
        at com.onedrive.sdk.http.BaseRequest.send(BaseRequest.java:198)
        at com.onedrive.sdk.generated.BaseItemRequest.update(BaseItemRequest.java:66)
        at com.jetico.bestcrypt.file.onedrive.OneDriveFile$12.execute(OneDriveFile.java:778)
        at com.jetico.bestcrypt.cloud.OneDriveCloud.requestToOneDrive(OneDriveCloud.java:147)
        at com.jetico.bestcrypt.file.onedrive.OneDriveFile.renameTo(OneDriveFile.java:767)
        at com.jetico.bestcrypt.file.onedrive.OneDriveFile.renameTo(OneDriveFile.java:556)
        at com.jetico.bestcrypt.service.CopyService.move(CopyService.java:678)
        at com.jetico.bestcrypt.service.CopyService.onHandleIntent(CopyService.java:232)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
```

 The problem is absent on a device with API level 21 inside of OneDrive Business.

**Comment by peternied** [comment]
This is the reason that I have not fixed bug #16 with the HTTP override yet, I'm still working on getting that scenario resolved for ODB
