### ISSUE TITLE
IllegalArgumentException in ADAL authentication on Android 4.1x

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#67]
When trying to authenticate (first time, interactive) for an ADAL account, the app crashes with the following exception:

> E/AndroidRuntime( 5976): FATAL EXCEPTION: pool-5-thread-1
> E/AndroidRuntime( 5976): java.lang.IllegalArgumentException: rawBytes
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.getSecretKey(StorageHelper.java:211)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:165)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:319)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:113)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:179)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1717)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1697)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:62)
> E/AndroidRuntime( 5976):        at com.microsoft.aad.adal.AuthenticationContext$5.run(AuthenticationContext.java:913)
> E/AndroidRuntime( 5976):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
> E/AndroidRuntime( 5976):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
> E/AndroidRuntime( 5976):        at java.lang.Thread.run(Thread.java:856)

This happens on Android 4.1x only (I tested on a Samsung Galaxy S2 and a Samsung Note II), it works on any other device I tested so far.

**Comment by 1gravity** [comment]
Closed for https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/571
