### ISSUE TITLE
Documentation example doesn't work

### ISSUE THREAD

**Issue by NLLAPPS** [OneDrive/onedrive-sdk-android#7]
I am trying to implement OneDrive Android SDK, so I've created a sample app, and added Auth section of your quick start guide then called

```
  final IOneDriveClient oneDriveClient = new OneDriveClient
                        .Builder()
                        .fromConfig(oneDriveConfig)
                        .loginAndBuildClient(MainActivity.this);
```

It does not invoke OAuth, silently fails and writes exception below

```
1-17 22:44:12.703 13161-14431/com.example.admin.myapplication I/LiveAuthClient: No refresh token available, sorry!
11-17 22:44:12.703 13161-14431/com.example.admin.myapplication I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
11-17 22:44:12.713 13161-14431/com.example.admin.myapplication E/MSAAuthenticator$5[onAuthComplete] - 262: Was unable to connect to the MSA login session
                                                                                                           com.onedrive.sdk.authentication.ClientAuthenticatorException: Was unable to connect to the MSA login session
                                                                                                               at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:260)
                                                                                                               at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
                                                                                                               at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
                                                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                               at java.lang.Thread.run(Thread.java:818)
11-17 22:44:12.763 13161-13161/com.example.admin.myapplication I/WebViewFactory: Loading com.google.android.webview version 46.0.2490.76 (code 249007650)
```

So I have tried the following 

```
new OneDriveClient
                        .Builder()
                        .fromConfig(oneDriveConfig)
                        .loginAndBuildClient(MainActivity.this).getAuthenticator().login("");

which again silently failed with 


11-17 22:46:18.132 17709-18740/com.example.admin.myapplication I/LiveAuthClient: No refresh token available, sorry!
11-17 22:46:18.132 17709-18740/com.example.admin.myapplication I/LiveAuthClient: All tokens expired, you need to call login() to initiate interactive logon
11-17 22:46:18.132 17709-18740/com.example.admin.myapplication E/MSAAuthenticator$5[onAuthComplete] - 262: Was unable to connect to the MSA login session
                                                                                                           com.onedrive.sdk.authentication.ClientAuthenticatorException: Was unable to connect to the MSA login session
                                                                                                               at com.onedrive.sdk.authentication.MSAAuthenticator$5.onAuthComplete(MSAAuthenticator.java:260)
                                                                                                               at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:484)
                                                                                                               at com.microsoft.services.msa.LiveAuthClient$3.doInBackground(LiveAuthClient.java:473)
                                                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                               at java.lang.Thread.run(Thread.java:818)
```

Finally I have tried this

```
       new OneDriveClient
                        .Builder()
                        .fromConfig(oneDriveConfig)
                        .loginAndBuildClient(MainActivity.this, new ICallback<IOneDriveClient>() {

                            @Override
                            public void success(IOneDriveClient client) {

                            }

                            @Override
                            public void failure(ClientException ex) {

                            }
                        });
```

which  although exception below was logged; it was able to invoke login window. Unfortunately login window is not optimised for mobile either (see attached).

Is it possible to post a sample app so developers would have some idea about correct way of authenticating/uploading etc. ?
Thank you

![screenshot_2015-11-17-22-50-34](https://cloud.githubusercontent.com/assets/14060247/11227442/e3fb27ca-8d7d-11e5-9517-c061cccaf606.png)

**Comment by peternied** [comment]
Sorry you are having trouble getting started, there is a fully functional example https://github.com/OneDrive/onedrive-explorer-android .

You can see how it creates its OneDriveClient, within its [BaseApplication.java@160](https://github.com/OneDrive/onedrive-explorer-android/blob/master/app/src/main/java/com/microsoft/onedrive/apiexplorer/BaseApplication.java#L160). 

Keep reusing this thread if you are having issues getting started

The exception that seeing from the silent is authentication is expected but not clear #8
And the improperly rendering I'll track with #9

**Comment by NLLAPPS** [comment]
Thanks very much.

Do you thing is there an issue with strong reference to Activity? I can see that requirement for Actvity reference comes form msa-auth-for-android.

It looks like you always have to pass an Activity to get the client. Is there any examples with just the Context? How would an Android Service initiate/create OneDriveClient?

In my usage case OneDrive client always used form a service once user authenticates from an Activity

**Comment by smorloc** [comment]
@NLLAPPS, I am having the same problem with the onedrive-explorer-android application.  I've just created an issue in that project.

**Comment by peternied** [comment]
With the current design an activity is necessary to display the interactive login window.  You could create a broker authenticator that you'd use in your application communicate with the service independent of an activity.

**Comment by peternied** [comment]
@NLLAPPS @smorloc With the recent fixes associated with authentication I'm going to close out this issue.  If you are still seeing trouble with a specific area please open a new issue to track that request or question.  Thanks!

**Comment by sw-dev1** [comment]
@peternied Could you elaborate on the idea of a "broker authenticator"? Is it possible to keep a persistent OneDriveClient object for use in an android service? Where should this object live between the service runs? Thanks.

**Comment by peternied** [comment]
With the [IAuthenicator](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/authentication/IAuthenticator.java) interface the contract is that the implementation just return a [IAccountInfo](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/authentication/IAccountInfo.java) object.  Inside of that implementation you could ignore the requirements around having an Activity (by just passing null) and use a broadcast notification or other layer to obtain the authentication tokens via the existing IAuthenticator implementations or your own variant.
