### ISSUE TITLE
I can't upload files with chinese title to OneDrive personal

### ISSUE THREAD

**Issue by yanbli** [OneDrive/onedrive-sdk-android#81]
This issue has been fixed on latest version 1.2.0. But there is another issue,

For OneDrive personal, I can't upload the file with Chinese title. for English title file, it is fine.
For OneDrive business, all file can be uploaded.

Do you know why?

the log is 
311: Error during http request
com.onedrive.sdk.core.ClientException: Error during http request
  at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:308)
  at com.onedrive.sdk.http.DefaultHttpProvider.access$000(DefaultHttpProvider.java:48)
  at com.onedrive.sdk.http.DefaultHttpProvider$1.run(DefaultHttpProvider.java:137)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.NoSuchElementException
  at java.util.Scanner.next(Scanner.java:968)
  at java.util.Scanner.next(Scanner.java:941)
  at com.onedrive.sdk.http.DefaultHttpProvider.streamToString(DefaultHttpProvider.java:383)
  at com.onedrive.sdk.http.OneDriveServiceException.createFromConnection(OneDriveServiceException.java:299)
  at com.onedrive.sdk.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:337)
  at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:251)
  at com.onedrive.sdk.http.DefaultHttpProvider.access$000(DefaultHttpProvider.java:48) 
  at com.onedrive.sdk.http.DefaultHttpProvider$1.run(DefaultHttpProvider.java:137) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
  at java.lang.Thread.run(Thread.java:818) 

I catch some http package:
the response code is 400.

**Comment by skvalex** [comment]
The same issue with Cyrillic characters, please fix the the problem as soon as it possible.

https://github.com/OneDrive/onedrive-api-docs/issues/371

**Comment by skvalex** [comment]
@daboxu have you tried your fix with the server? As I was always using urlencode to create the request:
UploadSession uploadSession = mClient.getDrive()
                    .getSpecial(APPROOT)
                    .getItemWithPath(URLEncoder.encode(path, "UTF-8"))
                    .getCreateSession(new ChunkedUploadSessionDescriptor())
                    .buildRequest()
                    .post();
Now it always returns me 400 Bad Request.
I used the following string to test: [Баланс汉语]_[0500]_2016-05-26_03-01-10.craf

That's how the request looks like: https://api.onedrive.com/v1.0/drive/special/approot:/%5B%D0%91%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%E6%B1%89%E8%AF%AD%5D_%5B0500%5D_2016-05-26_03-01-10.craf:/upload.createSession

**Comment by daboxu** [comment]
@skvalex thanks for providing the url, I can repro with it and has pushed a server side change. Will be back when server side issue has been fixed.

**Comment by yanbli** [comment]
@skvalex When can it work? Can you provide a ETA?

**Comment by skvalex** [comment]
@yanbli the question should be addressed to @daboxu. I'm in the same situation as you are.

**Comment by yanbli** [comment]
@daboxu in sdk 1.2.1 Do I need to encode the path? I find if don't encode the path for onedrive personal, it can work. But it doesn't work for onedrive business no matter encode the path

**Comment by daboxu** [comment]
You don't need encode the path. What error are you seeing for business account in logcat? I tested with business account and had no problem.

**Comment by yanbli** [comment]
Thanks @daboxu for replying. It works now.
