### ISSUE TITLE
Uploading of file failed

### ISSUE THREAD

**Issue by OlegRy** [OneDrive/onedrive-sdk-android#85]
I've authorized through SDK in my application and now I want upload file from device to OneDrive. I have permissions : "onedrive.readwrite", "onedrive.appfolder" , "wl.offline_access". There's a method for uploading:

``` java
public void importFile(File file) {
        if (mClient == null) return;
        Item result = mClient.getDrive().getSpecial("approot")
                .getChildren()
                .byId(file.getName())
                .getContent()
                .buildRequest()
                .put(FileUtil.convertToByteArray(file));
}
```

This method generates request URL like this: https://api.onedrive.com/v1.0/drive/special/approot/children/myFile.jpg/content and I catch an Exception with next stacktrace:
` FATAL EXCEPTION: IntentService[SyncApiService]
                                                                Process: com.rcd.perfecto, PID: 4368
                                                                com.onedrive.sdk.http.OneDriveServiceException: Error code: Unable to parse error response message
                                                                Error message: Raw error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: AD2DA6DF3ABB4DD19E05CC6B90E54421 Ref B: 53064A99C83854E658132D84D757A7DB Ref C: Wed Jun 01 09:00:06 2016 PST</span></div></div></body></html>

```
                                                            PUT https://api.onedrive.com/v1.0/drive/special/approot/children/PANO_20160524_154957.jpg/content
                                                            X-RequestStats : SDK-Version=Android-v1.1.3
                                                            Authorization : bearer EwCIAq1DBAAUGCCXc8wU/zFu9Qn[...]
                                                            byte[1888628] {-1, -40, -1, -31, 1, 111, 69, 120, [...]

                                                            503 : Service Unavailable
                                                            [...]

                                                            [Some information was truncated for brevity, enable debug logging for more details]
                                                                at com.onedrive.sdk.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:329)
                                                                at com.onedrive.sdk.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:243)
                                                                at com.onedrive.sdk.http.DefaultHttpProvider.send(DefaultHttpProvider.java:154)
                                                                at com.onedrive.sdk.http.BaseStreamRequest.send(BaseStreamRequest.java:98)
                                                                at com.onedrive.sdk.generated.BaseItemStreamRequest.put(BaseItemStreamRequest.java:68)
                                                                at com.rcd.perfecto.utils.storages.helpers.OneDriveHelper.importFile(OneDriveHelper.java:100)
                                                                at com.rcd.perfecto.utils.storages.helpers.StoragesHelper.importFile(StoragesHelper.java:438)
                                                                at com.rcd.perfecto.utils.storages.helpers.StoragesHelper.importFilesIfExist(StoragesHelper.java:104)
                                                                at com.rcd.perfecto.services.SyncApiService.importFilesToClouds(SyncApiService.java:1078)
                                                                at com.rcd.perfecto.services.SyncApiService.uploadNewFilesSync(SyncApiService.java:922)
                                                                at com.rcd.perfecto.services.SyncApiService.startFileSync(SyncApiService.java:859)
                                                                at com.rcd.perfecto.services.SyncApiService.handleActionFullSync(SyncApiService.java:251)
                                                                at com.rcd.perfecto.services.SyncApiService.onHandleIntent(SyncApiService.java:212)
                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)`
```

I've tried send the same request through apigee.com and all works fine. So what am I doing wrong?

**Comment by skvalex** [comment]
@OlegRy you need to update SDK up to the version 1.2.0: https://github.com/OneDrive/onedrive-sdk-android/issues/79#issuecomment-221688250

**Comment by peternied** [comment]
@OlegRy Please reopen if this is still an issue.
